#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, 
	KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, 
	LALT(KC_RGHT), LCTL_T(KC_A), LGUI_T(KC_S), LALT_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RALT_T(KC_K), RGUI_T(KC_L), RCTL(KC_SCLN), KC_QUOT, 
	LALT(KC_LEFT), KC_Z, LT(1,KC_X), LT(2,KC_C), LT(3,KC_V), KC_B, KC_N, LT(3,KC_M), LT(2,KC_COMM), LT(1,KC_DOT), KC_SLSH, RALT(KC_LEFT), 
	DRGSCRL, KC_SPC, KC_BSPC, MS_BTN1, KC_ENT, MS_BTN1, MS_BTN2, MS_BTN2),
    [1] = LAYOUT(KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_UNDS, 
	KC_TRNS, KC_PSCR, KC_NO, KC_UP, KC_NO, LALT(KC_F4), KC_LBRC, KC_P7, KC_P8, KC_P9, KC_RBRC, KC_NUM, 
	KC_TRNS, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, LALT(KC_LEFT), KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PMNS, KC_PEQL, 
	KC_TRNS, KC_NO, KC_PGUP, KC_PGDN, LALT(KC_LEFT), LALT(KC_RGHT), KC_PAST, KC_P1, KC_P2, KC_P3, KC_PSLS, KC_PDOT, 
	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0),
    [2] = LAYOUT(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, 
	KC_TRNS, KC_PSCR, KC_NO, KC_UP, KC_NO, LALT(KC_F4), KC_LBRC, KC_P7, KC_P8, KC_P9, KC_RBRC, KC_NUM, 
	KC_TRNS, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, LALT(KC_LEFT), KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PMNS, KC_PEQL, 
	KC_TRNS, KC_NO, KC_PGUP, KC_PGDN, LALT(KC_LEFT), LALT(KC_RGHT), KC_PAST, KC_P1, KC_P2, KC_P3, KC_PSLS, KC_PDOT, 
	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0),
    [3] = LAYOUT(KC_ESC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	KC_TRNS, KC_DEL, KC_TRNS, DPI_RMOD, S_D_RMOD, LALT(KC_F4), KC_TRNS, S_D_MOD, DPI_MOD, KC_TRNS, KC_TRNS, KC_TRNS, 
	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LALT(KC_LEFT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
	KC_TRNS, KC_TRNS, DRGSCRL, SNIPING, LALT(KC_LEFT), LALT(KC_RGHT), KC_TRNS, KC_TRNS, SNIPING, DRGSCRL, MS_BTN3, KC_TRNS, 
	KC_TRNS, MS_BTN3, KC_TRNS, KC_TRNS, MS_BTN3, KC_TRNS, KC_TRNS, KC_TRNS),
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
